---
title: "Assignment 02"
subtitle: "C++ Object-oriented Programming"
author:
    Khiem Nguyen 
    <br> Lecturer in Multiscale Materials
    <br> <khiem.nguyen@glasgow.ac.uk>
author-meta: "Lecturer in Multiscale Materials"
jupyter: false
execute: 
  eval: true
format: 
    html:
        code-line-numbers: true
        output-file: "mock.html"
        embed-resources: true
        grid:
            body-width: 1600px
            margin-width: 20px
            sidebar-width: 200px
        # page-layout: full
        # margin-left: 0.5em
        # margin-right: 0.5em
       
        css: style.css
        number-sections: true
        number-depth: 3
        toc: true               # table of content
        toc-location: left      # table of content on the left
        toc-title: "Table of Content"   # table of content title

    # pdf:
    #     output-file: "01-description.pdf"
    #     embed-resources: true
    #     geometry:
    #         - top=24px
    #         - bottom=24px
    #         - left=36px
    #         - right=36px
    #     css: style.css
    #     number-sections: true
    #     number-depth: 2
    #     toc: true               # table of content
    #     toc-location: left      # table of content on the left
    #     toc-title: "Table of Content"   # table of content title
    #     colorlinks: true
---

# Foreword

## Structure of the paper exam

The real paper exam contains $3$ questions with the following grade distribution:

| Question    | Grade  |
|:------------|:-------|
| Q1: C++ Theory  | 30     |
| Q2: Writing C++ Code  | 40     |
| Q3: UML Class diagram  | 30     |

## How to pass the course

Over the the past two years I received two common questions. I believe that it is good to write down my answers so that you understand the course's demand, and my philosophy.

- **Question 1**: Can I pass the entire course with $0$ on the paper exam because I have already achieved $80\%$ on the $50\%$ of the course grade (coursework as continous assessment)

    **Answer**: No, you won't. According to the UoG's guideline, you need to pass any component constituting of more than $30\%$ of the course grade by the minimum **E3** (namely 30 points out of 100 points). In general, I am happy to pass somebody with $28 -- 29$ points with true effort. But if that somebody got $28$ points due to my gentle marking, I still need to fail them. For example, I give $1$ point for every attempt while the answers are all wrong and your grade cannot still cross the threshold $30$ points, you deserve a fail even at the boundary $29$ points. If I pass these students, they will continue to build airplanes, security softwares and then we will all die.

- **Question 2**:  Can I pass the exam by learning everything by heart without understanding the logics or should I understand the logic?

    **Answer**: This question sounds irony but it is completely legitimate. Here is my thought. First, exams are deisnged to test your knowledge, not to test your memory. So, without understanding the logics, I think you will likely fail. Second, I don't believe that that anybody can learn $200$ lines of code by heart and can apply what they memorize to another applications without understanding a single thing. In doing that, you have already understood something. If you believe that you already learned $200$ lines of code by heart but you could not apply what you did to a similar application, then you actually did not learn anything by heart.

## What to review

When I was a student, my professors always answer the question "what to review?" by a single sentence: "Everything we have learned so far". That's all, no further elobration. Personally, I think this should be a standard question for such a question too. What's the point if you can pass an exam by knowing a very specific area. You are educated to work in real-world environment, not to pass the exams.

Saying that, this is my advice. You should at least understand the following important concepts and know how to implement them in C++ code.

- **Basics of C++**: To understand the code and to understand exam's questions, of course you need to know and understand the basics of C++.
    - [**Iteration statements**]{style="color:red"}: `for` loop`, `while` loop, `do-while` loop
    - [**Condition statements**]{style="color:red"}: `if` statement, `if-else` statement, `if-else-if` statement
    - [**Functions**]{style="color:red"}: function definition, parameters versus arguments, return value of a function

- **Intermediate of C++**: The question of C++ theory basically may ask you anything we have learned so far from the lectures. However, these are the concepts you may want to pay good attention on
    - [**reference**]{style="color:blue"}, [*pass by reference*]{style="color:blue"} versus [*pass by value*]{style="color:blue"} in writing functions
    - [**pointer**]{style="color:blue"}, [*pass by pointer*]{style="color:blue"} (frequenly called [*pass by address*]{style="color:blue"})
    - [**template**]{style="color:blue"}: function template, class template

- **Object-oriented programming**: Of course, you should be able to implement very basics of object-oriented programming paradigm.
    - [**class**]{style="color:brown"}: define a class, write a constructor, write a destructuor, list initializer for constructor, etc.
    - [**access speficiers**]{style="color:brown"}: `private`, `public` and `protected`. `protected` is rarely used but you may at least need to be aware of this.
    - [**overriding operators**]{style="color:brown"}: override operator `<<` (output the object), arithmetic operators `+` (addition), `-` (subtraction), `*` (multiplication), etc.
    - [**inheritance**]{style="color:brown"}: basic concept of inheritance, how to define a child class
    - [**polymorphism**]{style="color:brown"}: basic concept of polymorphism, how to implement polynomorphism for children classes using `virtual function`.
    - [**abstract class**]{style="color:brown"}: basic concept of abstract class, how to make a class abstract.

That sounds a lot!?!? **Not really**. If you practice **Question 2:: Writing C++ Code**, you have reviewed most of the important points here.

# Mock exam

The **mock exam** here follows similar structure of the **real exam** with of course different questions in the part asking C++ theories and a different application in the question asking writing C++ code, and in drawing UML class diagram.

:::{.callout-warning}
# Appearance of the real exam vs the mock exam

The real paper exam is prepared by LaTeX. So you should see that the questions look like in the past paper exam, namely (a), (b), $\ldots$, (g). However, this mock exam is prepared by using Quarto. [Therefore, the appearance of this mock exam may not look exactly the same as the real one although they are essentially the same. The content is tremendously helpful for the real paper exam though.]{style="color:blue"}
:::

:::{.callout-note}
# Learn the logics behind the mock exam
- [Note that the **real exam** is **definitely much shorter than** the **mock exam** here.]{style="color:red"} The mock exam is longer because I want to provide an opportunity for you to "really learn", not to "remember by heart".
- I struggle preparing this mock exam because I don't want it to be so similar to the real paper exam. But I don't want it to be completely different from the real exam. What's the point of a mock exam if it is completely different? 
- [**So you should learn the programming logics behind this mock exam, don't try to learn it by heart.**]{style="color:red"}
:::

## Question 1: C++ Theory


### Question A

**(a)**&nbsp; You are given the following code snippet:

```{.cpp}
#include <iostream>

// 1. Increments the value of 'n' by 10 using a pointer.
void increment_by_pointer(int* ptr) {
    // Write code here
}

// 2. Doubles the value of 'n' using a reference.
void double_by_reference(int& ref) {
    // Write code here
}

// 3. Swaps the address held by two pointers (Pointer to Pointer).
// Note: This should change where the pointers in main point to.
void swap_pointers(int** ptr1, int** ptr2) {
    // Write code here
}

int main() {
    int a { 5 };
    int b { 50 };
    
    int* pA { &a };
    int* pB { &b };

    // Task 1: Use increment_by_pointer to make 'a' equal to 15.
    // Task 2: Use double_by_reference to make 'b' equal to 100.
    // Task 3: Use swap_pointers so that pA points to 'b' and pB points to 'a'.

    return 0;
}
```

**Question**: 

- Write the implementation for `increment_by_pointer()`, for `double_by_reference()` and `swap_pointers()`. 
- Write the three lines of code inside `main()` required to call these functions correctly using the variables provided. 
- You only need to missing code -- don't rewrite what have been provided. You may need to write the line number shown on the code for easy navigation.


**(b)**&nbsp; You are given the following code snippet:

```{.cpp}
#include <iostream>
#include <string>

class Student {
private:
    std::string name;
    mutable int access_count { 0 };

public:
    Student(std::string name) : name {name} {}

    // A: Returns the name
    std::string get_name() const { 
        access_count++; 
        return name; 
    }

    // B: Sets a new name
    void set_name(std::string n) { 
        name = n; 
    }
};

int main() {
    Student std_01 {"Tony Stark"};
    const Student std_02 {"Hulk"};

    // Line 1: Pointer to a constant Student
    const Student* ptr = &s1;
    ptr->set_name("New Name");

    // Line 2: Constant pointer to a Student
    Student* const cptr = &s2;
    cptr->set_name("New Name");

    // Line 3: Method call
    std::cout << s2.get_name() << " accessed " << std::endl;

    return 0;
}
```

**Question**

- **Analyze Line 1 and Line 2**: Both lines will cause a compilation error. Explain the difference between `const Student*` and `Student* const` and why each specific line fails.
- **Analyze Method A** (`get_name`): Even though this method is marked `const`, it modifies `access_count`. Explain why this code **will** compile and what the `mutable` keyword achieves in this context. What happens if we remove `mutable`?
- **Analyze Line 3**: If the `const` qualifier were removed from the declaration of `get_name()`. Line 3 would fail to compile. Explain why a `const` object like `std_02` can only call `const` member functions.


### Answer




**(c)**&nbsp; You are given the following code snippet:

```{.cpp}
#include <iostream>
#include <string>

// --- Write your Function Template here ---


// -----------------------------------------

struct Box {
    int volume;
    // Overloading the > operator for Box comparison
    bool operator>(const Box& other) const {
        return volume > other.volume;
    }
};

int main() {
    // Test Case 1: Integers
    int a { 10 }, b { 20 };
    std::cout << "Max int: " << find_max(a, b) << '\n';

    // Test Case 2: Strings
    std::string s1 { "Apple" }, s2 { "Zebra" };
    std::cout << "Max string: " << find_max(s1, s2) << '\n';

    // Test Case 3: Custom Objects
    Box b1 { 500 }, b2 { 1000 };
    Box biggest = find_max(b1, b2);
    std::cout << "Max Box volume: " << biggest.volume << '\n';

    return 0;
}
```

**Question**

- Write the full definition of the function template `find_max`. It should take two parameters of the same template type by reference to const and return the result by value.
- In **Test Case 3**, the code compiles because the `Box` structu has overloaded `operator>`. If this operator was **not** overloaded, what specific error would the compiler generate when trying to instatiate the template?
- If the function was called as `find_max(41.3, 3.14)`, the compiler would fail to deduce the template argument. Eplain why this happens and provide two ways a developer could fix the call in `main()` witout changing the template definition.